config/routes.rb
Rails.application.routes.draw do
  
  root 'artists#index'

  resources :artists do
    resources :songs
  end
  
  resources :billboards do
    resources :songs do
      put :add
      end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
require 'pry'

class ArtistsController < ApplicationController
  before_action :find_artist, only: [:show, :edit, :update, :destroy]
  
  def index
    @artists = Artist.all
  end

  def show
    @songs = @artist.songs.all
    @song = @artist.songs.new

  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private 
    def find_artist
      @artist = Artist.find(params[:id])
    end
    
    def artist_params
      params.require(:artist).permit(:name)
    end
    
end

app/controllers/billboards_controller.rb
require 'pry'
class BillboardsController < ApplicationController

  before_action :find_billboard, only: [:show, :edit, :update, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboard_path(@billboard)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end  

  
  

  private

    def billboard_params
      params.require(:billboard).permit(:name)
    end

    def find_billboard
      @billboard = Billboard.find(params[:id])
    end
    
end

app/controllers/songs_controller.rb
require 'pry'

class SongsController < ApplicationController
    before_action :find_artist, only: [:destroy, :add]

    def create
        @artist = Artist.find(params[:artist_id])
        @song = @artist.songs.new(song_params)
        @song.save
        redirect_to artist_path(params[:artist_id])  
    end

    def destroy
        @song.destroy
        redirect_to artist_path(params[:artist_id])
    end

    def add
        song.billboard_id = params[:billboard_id]
        song.save

        redirect_to billboard_path(params[:billboard_id])
    end

    private

        def song_params
            params.require(:song).permit(:title)
        end

        def find_artist
            song = Song.find(params[:song_id])
        end
        

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist <%= @artist.name %></h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<% if @artists.empty? %>
    <h3>You don't have any artists to display.</h3>
<% else %>
    <% @artists.each do |artist| %>
    <%= link_to artist.name, artist_path(artist) %>
    <span> --- </span>
    <%= link_to 'Edit', edit_artist_path(artist) %>
    <span> --- </span>
    <%= link_to 'Delete', artist_path(artist), method: :delete %>
    <% end %>
<% end %>
<br>
<br>
<%= link_to  'Back to Billboards', billboards_path %>
<%= link_to 'Create New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>Create New Artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<h1>Artist: <%= @artist.name %></h1>

<h2>Songs:</h2>
    <ol>
        <% @songs.each do |song| %>
        <li><%= song.title %>
        <span> --- </span>
        <%= link_to 'Delete', artist_song_path(@artist, song), method: :delete %>
        </li>
        <% end %>
    </ol>



<p>Add New Song</p>


<%= form_for [@artist, @song] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit %>
<% end %>


<%= link_to 'Back to Artists List', artists_path %>

app/views/billboards/_form.html.erb
<%= form_for @billboard do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard <%= @billboard.name %></h1>

<%= render 'form' %>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<% if @billboards.empty? %>
    <h3>You don't have any billboards to display.</h3>
<% else %>
    <% @billboards.each do |billboard| %>
        <%= link_to billboard.name, billboard_path(billboard) %>
        <span> --- </span>
        <%= link_to 'Edit', edit_billboard_path(billboard) %>
        <span> --- </span>
        <%= link_to 'Delete', billboard_path(billboard), method: :delete %>
        <br>
    <% end %>
<% end %>
<br>
<%= link_to 'New Billboard', new_billboard_path %>

app/views/billboards/new.html.erb
<h3>New Billboard</h3>


<%= render 'form' %>

app/views/billboards/show.html.erb
<h1>Billboard: <%= @billboard.name %></h1>

<h3>Songs:</h3>

<% if @billboard.songs.empty? %>
    <h3>You have no songs assigned to this billboard.</h3>
<% else %>
    <ol>
        <% @billboard.songs.each do |song| %>
        <li>
            <%= song.title %> by <%= Artist.find(Song.find(song.id).artist_id).name %>
        </li>
        <% end %>
    </ol>
<% end %>


Add Song to Billboard:

<ol>
    <% Song.all.each do |song| %>
        <li>
            <%= song.title %> by <%= Artist.find(Song.find(song.id).artist_id).name %>
            <%= link_to "Add", billboard_song_add_path(@billboard, song), method: :put %>
        </li>
    <% end %>
</ol>

<%= link_to 'Back to Billboard List', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBillboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>